name: Code testing
on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Lint command
              run: eslint --ext .jsx --fix src

    test:
        runs-on: ubuntu-latest
        needs: lint      
        steps:
            - name: Run Test script
              run: vitest run

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Deploy website
              run: vite build